services:
  open-live-trivia-fe:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
      - $HOME/.open-live-trivia_vault/fe.env:/app/env/fe.env:ro
      - $HOME/.open-live-trivia_vault/fe-secrets.env:/app/env/fe-secrets.env:ro
    tty: true
    stdin_open: true

networks:
  open-live-trivia_network:
    driver: bridge
