FROM node:22-alpine

WORKDIR /app

COPY package.json package-lock.json ./

ENV ENV_FILE=/app/fe.env
ENV SECRETS_ENV_FILE=/app/fe-secrets.env
RUN npm install

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
