services:
  open-live-trivia-fe:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
      - $HOME/.open-live-trivia_vault/fe/firebase-config.js:/app/firebase-config.js:ro
      - $HOME/.open-live-trivia_vault/fe/config.js:/app/config.js:ro
    tty: true
    stdin_open: true

networks:
  open-live-trivia_network:
    driver: bridge
