name: open-live-trivia-fe

services:
  open-live-trivia-fe:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: open-live-trivia-fe
    restart: unless-stopped
    networks:
      - ${NETWORK_NAME:-open-live-trivia_network}

